### ISSUE TITLE
Trabajo final: Base de Datos

### ISSUE THREAD

**Issue by santyagote** [Grupazo-5/Trabajo-integrador#2]
Acá vamos a ir agregando todo lo relacionado al eje de Base de Datos

**Comment by SrLachy** [comment]
Aquí adjunto el archivo de las entidades y sus relaciones.
[Entidades y atributos.docx](https://github.com/user-attachments/files/15539725/Entidades.y.atributos.docx)

**Comment by javiGomezCba** [comment]
Aquí adjunto el diagrama relacional.

[Diagrama Relacional.drawio.pdf](https://github.com/user-attachments/files/15637664/Diagrama.Relacional.drawio.pdf)
