### ISSUE TITLE
Trabajo final: Ética

### ISSUE THREAD

**Issue by santyagote** [Grupazo-5/Trabajo-integrador#3]
Acá vamos a ir agregando todo lo relacionado al eje de Ética

**Comment by ccauci** [comment]
Adjunto el archivo de Etica (el primero esta en formato PDF y el segundo es el link de docs.google para que pueda ver el progreso)
[etica.docx.pdf](https://github.com/user-attachments/files/15597582/etica.docx.pdf)
https://docs.google.com/document/d/1pusDi7l34Ky8uMADL6IaiRyah6ROvDJf/edit
